### ISSUE TITLE
rosetta-grappelli is not a valid package name in Python

### ISSUE THREAD

**Issue by pwalsh** [belugame/django-rosetta-grappelli#4]
Causes fail when using with Satchmo, with uses an app called app_plugin.

RuntimeError at /admin/
invalid label: rosetta-grappelli
Request Method: GET
Request URL:    http://hamigdalor.dev:8000/admin/
Django Version: 1.4.2
Exception Type: RuntimeError
Exception Value:  
invalid label: rosetta-grappelli

**Comment by belugame** [comment]
Satchmo has not seen a commit in 6 years, so even more dead than this here ;)
Closing since I believe it has no relevance for any user out there.
