### ISSUE TITLE
Release a new version to pypi.python.org

### ISSUE THREAD

**Issue by kairichard** [belugame/django-rosetta-grappelli#7]
The currently available version on pypi still is not compatible with django>=1.5.
Please upload a new one so we dont have to pinpoint the downloadable zip in our
requirements.txt

**Comment by belugame** [comment]
@esquevin  ￼@jauneau
Would you enable someone else to make a release by giving write-access to the project?

**Comment by esquevin** [comment]
I transferred the ownership of this repository to you. You should be able to accept it and then you'll be able to write, deploy and do whatever you need =)

Thank you

**Comment by belugame** [comment]
@esquevin  Thank you very much, the link sadly expired before I could accept it. Could you try again?

**Comment by esquevin** [comment]
Should be good now

Guillaume Esquevin

**Comment by belugame** [comment]
See here for the new pypi project page and the 1.1 release: https://pypi.python.org/pypi/django-rosetta-grappelli2/
