### ISSUE TITLE
A new feature of Rosetta does not work with Django-Rosetta-Grappelli

### ISSUE THREAD

**Issue by egor83** [belugame/django-rosetta-grappelli#9]
'Reference language' feature, added in [Rosetta's #60](https://github.com/mbi/django-rosetta/pull/60), does not work with Django-Rosetta-Grappelli: relevant portion of the pofile.html is rewritten by D-R-G:
https://github.com/mbi/django-rosetta/pull/60/files#diff-c12dca8ac51c7fbeb2a10d0d8ef29020

Some more discussion in [Rosetta's #180](https://github.com/mbi/django-rosetta/issues/180).

**Comment by kairichard** [comment]
@egor83 Thanks for your report, we have transferred the repo to https://github.com/PaesslerAG/django-rosetta-grappelli in the mean time. It would be totally awesome if you could open up the issues on the repo's new home again as we cannot move issues between projects. Thanks in advance.

**Comment by egor83** [comment]
@kairichard Tried to open an issue there, but I just don't see an "Issues" tab - maybe you need to explicitly enable issues on a forked repo?

https://stackoverflow.com/questions/16406180/is-there-a-way-to-add-issues-to-a-github-forked-repo-without-modifying-the-orig
https://help.github.com/articles/disabling-issues/

**Comment by kairichard** [comment]
@egor83 thanks a lot for the hint - I didn't know one had to explicitly enable Issues for forked repos. Now the new repos also has issues.

**Comment by egor83** [comment]
@kairichard You're welcome! Moved there, closing.
